version: '3.3'

services:
  web:
    build: .
    volumes: 
      # - .:/usr/src/app
      - static:/usr/src/app/static 
    ports:
      - 8000:8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/app/static 
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static:
