# Generated by Django 4.0.2 on 2022-02-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontoturistico_imagem_alter_pontoturistico_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='imagem',
            new_name='foto',
        ),
    ]
