# Generated by Django 4.0.2 on 2022-03-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_imagem_pontoturistico_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrtion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='doc_rg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.docrg'),
        ),
    ]
