# Generated by Django 4.0.2 on 2022-03-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_docrg_pontoturistico_doc_rg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docrg',
            old_name='descrtion',
            new_name='desacrição',
        ),
    ]
