# Generated by Django 4.0.2 on 2022-02-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracoes',
            options={'verbose_name_plural': 'Atrações'},
        ),
    ]
