# Generated by Django 4.0.2 on 2022-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_alter_atracoes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracoes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
