# Generated by Django 4.0.2 on 2022-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_atracoes_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracoes',
            name='observacoes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
